"use client";

import { useState } from "react";
import { Button } from "@/components/ui/Button";
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from "@/components/ui/Card";
import {
  Download,
  Mail,
  Share2,
  FileText,
  Check,
  Copy,
  Printer,
} from "lucide-react";
import { formatCurrency, formatPercentage, getRateTypeLabel } from "@/lib/utils";
import type { RecommendationSet, Recommendation } from "@/types";

interface ExportRecommendationsProps {
  recommendations: RecommendationSet;
}

export function ExportRecommendations({
  recommendations,
}: ExportRecommendationsProps) {
  const [copied, setCopied] = useState(false);
  const [emailSent, setEmailSent] = useState(false);

  const generateTextSummary = (): string => {
    const { recommendations: plans, best_savings, generated_at } = recommendations;
    const date = new Date(generated_at).toLocaleDateString();

    let summary = `Energy Plan Recommendations - Generated ${date}\n`;
    summary += `${"=".repeat(50)}\n\n`;
    summary += `Potential Annual Savings: ${formatCurrency(best_savings)}\n\n`;

    plans.forEach((rec, index) => {
      summary += `#${index + 1} - ${rec.plan.name}\n`;
      summary += `-`.repeat(40) + `\n`;
      summary += `Provider: ${rec.plan.supplier?.name || "N/A"}\n`;
      summary += `Rate Type: ${getRateTypeLabel(rec.plan.rate_type)}\n`;
      summary += `Rate: $${Number(rec.plan.rate_per_kwh).toFixed(4)}/kWh\n`;
      summary += `Monthly Fee: ${formatCurrency(rec.plan.monthly_fee)}\n`;
      summary += `Contract: ${rec.plan.contract_length_months} months\n`;
      summary += `Renewable: ${formatPercentage(rec.plan.renewable_percentage)}\n`;
      summary += `Projected Annual Cost: ${formatCurrency(rec.projected_annual_cost)}\n`;
      summary += `Annual Savings: ${formatCurrency(rec.projected_annual_savings)}\n`;
      summary += `\nWhy this plan: ${rec.explanation}\n\n`;
    });

    summary += `\nGenerated by Arbor Energy Plan Agent\n`;
    return summary;
  };

  const generateCSV = (): string => {
    const { recommendations: plans } = recommendations;
    const headers = [
      "Rank",
      "Plan Name",
      "Supplier",
      "Rate Type",
      "Rate ($/kWh)",
      "Monthly Fee",
      "Contract (months)",
      "Renewable %",
      "Annual Cost",
      "Annual Savings",
      "Overall Score",
    ];

    const rows = plans.map((rec, index) => [
      index + 1,
      rec.plan.name,
      rec.plan.supplier?.name || "N/A",
      getRateTypeLabel(rec.plan.rate_type),
      Number(rec.plan.rate_per_kwh).toFixed(4),
      Number(rec.plan.monthly_fee).toFixed(2),
      rec.plan.contract_length_months,
      Number(rec.plan.renewable_percentage).toFixed(0),
      Number(rec.projected_annual_cost).toFixed(2),
      Number(rec.projected_annual_savings).toFixed(2),
      (Number(rec.overall_score) * 100).toFixed(1),
    ]);

    return [headers.join(","), ...rows.map((row) => row.join(","))].join("\n");
  };

  const handleCopyToClipboard = async () => {
    const text = generateTextSummary();
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error("Failed to copy:", err);
    }
  };

  const handleDownloadCSV = () => {
    const csv = generateCSV();
    const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `energy-recommendations-${new Date().toISOString().split("T")[0]}.csv`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handleDownloadText = () => {
    const text = generateTextSummary();
    const blob = new Blob([text], { type: "text/plain;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `energy-recommendations-${new Date().toISOString().split("T")[0]}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handlePrint = () => {
    window.print();
  };

  const handleEmailShare = () => {
    const subject = encodeURIComponent("My Energy Plan Recommendations");
    const body = encodeURIComponent(generateTextSummary());
    window.location.href = `mailto:?subject=${subject}&body=${body}`;
    setEmailSent(true);
    setTimeout(() => setEmailSent(false), 2000);
  };

  const handleShare = async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: "Energy Plan Recommendations",
          text: generateTextSummary(),
        });
      } catch (err) {
        if ((err as Error).name !== "AbortError") {
          console.error("Share failed:", err);
        }
      }
    } else {
      handleCopyToClipboard();
    }
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Share2 className="w-5 h-5 text-arbor-primary" aria-hidden="true" />
          Export & Share
        </CardTitle>
        <p className="text-sm text-gray-500 mt-1">
          Save or share your recommendations
        </p>
      </CardHeader>
      <CardContent>
        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-3">
          {/* Copy to Clipboard */}
          <Button
            variant="outline"
            onClick={handleCopyToClipboard}
            className="flex flex-col items-center gap-2 h-auto py-4"
          >
            {copied ? (
              <Check className="w-5 h-5 text-green-600" aria-hidden="true" />
            ) : (
              <Copy className="w-5 h-5" aria-hidden="true" />
            )}
            <span className="text-xs">{copied ? "Copied!" : "Copy Text"}</span>
          </Button>

          {/* Download CSV */}
          <Button
            variant="outline"
            onClick={handleDownloadCSV}
            className="flex flex-col items-center gap-2 h-auto py-4"
          >
            <Download className="w-5 h-5" aria-hidden="true" />
            <span className="text-xs">CSV</span>
          </Button>

          {/* Download Text */}
          <Button
            variant="outline"
            onClick={handleDownloadText}
            className="flex flex-col items-center gap-2 h-auto py-4"
          >
            <FileText className="w-5 h-5" aria-hidden="true" />
            <span className="text-xs">Text File</span>
          </Button>

          {/* Print */}
          <Button
            variant="outline"
            onClick={handlePrint}
            className="flex flex-col items-center gap-2 h-auto py-4"
          >
            <Printer className="w-5 h-5" aria-hidden="true" />
            <span className="text-xs">Print</span>
          </Button>

          {/* Email */}
          <Button
            variant="outline"
            onClick={handleEmailShare}
            className="flex flex-col items-center gap-2 h-auto py-4"
          >
            {emailSent ? (
              <Check className="w-5 h-5 text-green-600" aria-hidden="true" />
            ) : (
              <Mail className="w-5 h-5" aria-hidden="true" />
            )}
            <span className="text-xs">{emailSent ? "Opening..." : "Email"}</span>
          </Button>

          {/* Native Share */}
          <Button
            variant="outline"
            onClick={handleShare}
            className="flex flex-col items-center gap-2 h-auto py-4"
          >
            <Share2 className="w-5 h-5" aria-hidden="true" />
            <span className="text-xs">Share</span>
          </Button>
        </div>

        {/* Quick Summary Card for Print */}
        <div className="mt-6 print:block hidden">
          <h3 className="font-bold text-lg mb-4">Energy Plan Recommendations Summary</h3>
          <div className="text-sm text-gray-600 mb-2">
            Generated: {new Date(recommendations.generated_at).toLocaleDateString()}
          </div>
          <div className="text-sm font-semibold text-green-600 mb-4">
            Potential Savings: {formatCurrency(recommendations.best_savings)}/year
          </div>
          {recommendations.recommendations.map((rec: Recommendation, idx: number) => (
            <div key={rec.id} className="border-b py-4">
              <div className="font-semibold">
                #{idx + 1}: {rec.plan.name}
              </div>
              <div className="text-sm text-gray-600">
                {rec.plan.supplier?.name} | {getRateTypeLabel(rec.plan.rate_type)} |{" "}
                ${Number(rec.plan.rate_per_kwh).toFixed(4)}/kWh
              </div>
              <div className="text-sm mt-1">
                Annual Cost: {formatCurrency(rec.projected_annual_cost)} |
                Savings: {formatCurrency(rec.projected_annual_savings)}
              </div>
              <p className="text-sm text-gray-500 mt-2">{rec.explanation}</p>
            </div>
          ))}
        </div>
      </CardContent>
    </Card>
  );
}
